# Generated by Django 4.2.1 on 2023-05-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiensImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('prix', models.CharField(blank=True, max_length=255, null=True)),
                ('pieces', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
