# Generated by Django 4.2.1 on 2023-05-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biensimmobilier',
            name='page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
